### ISSUE TITLE
关于文章中参考模型参数量的问题

### ISSUE THREAD

**Issue by wangtianrui** [felixfuyihui/Uformer#1]
您好，我阅读了您的文章，想请教一个问题：
UFormer文章中表1中的DCCRN的参数量是8.99M。但是DCCRN原文中的参数量是3.7M。我想请问一下您文章中DCCRN的参数配置是怎么样的。您文章中的DCCRN是否性能是优于DCCRN原文的（因为从结果来看DCCRN甚至超过了DCCRN+）。谢谢！

**Comment by felixfuyihui** [comment]
大佬好，久仰久仰
先回答后一个问题。因为dccrn+也是参赛模型，所以我用的是dccrn+提交比赛的结果（这个模型作者当时训练时候没有做去混所以指标可能差点）。dccrn是我用跟proposed一样的数据和训练策略训的，能去混，所以效果好。（这个好像我有提到）
第一个问题，我主要我是想让dccrn的参数量跟proposed的差不多，所以我把中间lstm节点数增加了的（256*3层）而且是blstm为了获得更好的效果。应该是这个原因导致参数量跟原论文比大了。

**Comment by felixfuyihui** [comment]
> 大佬好，久仰久仰
> 先回答后一个问题。因为dccrn+也是参赛模型，所以我用的是dccrn+提交比赛的结果（这个模型作者当时训练时候没有做去混所以指标可能差点）。dccrn是我用跟proposed一样的数据和训练策略训的，能去混，所以效果好。（这个好像我有提到）
> 第一个问题，我主要我是想让dccrn的参数量跟proposed的差不多，所以我把中间lstm节点数增加了的（256*3层）而且是blstm为了获得更好的效果。应该是这个原因导致参数量跟原论文比大了。

**Comment by felixfuyihui** [comment]
> 大佬好，久仰久仰
先回答后一个问题。因为dccrn+也是参赛模型，所以我用的是dccrn+提交比赛的结果（这个模型作者当时训练时候没有做去混所以指标可能差点）。dccrn是我用跟proposed一样的数据和训练策略训的，能去混，所以效果好。（这个好像我有提到）
第一个问题，我主要我是想让dccrn的参数量跟proposed的差不多，所以我把中间lstm节点数增加了的（256*3层）而且是blstm为了获得更好的效果。应该是这个原因导致参数量跟原论文比大了。

**Comment by wangtianrui** [comment]
明白了。能比提升一倍参数量的DCCRN好也证明了UFormer的有效性。非常感谢你细心的答复。
