### ISSUE TITLE
DCCRN PLUS 的实现能开源吗

### ISSUE THREAD

**Issue by zuowanbushiwo** [felixfuyihui/Uformer#4]
你好
      我看你文章中有对比DCCRN plus，我目前没有找到这个开源的实现，你是否可以开源一下？谢谢！

**Comment by felixfuyihui** [comment]
> 你好 我看你文章中有对比DCCRN plus，我目前没有找到这个开源的实现，你是否可以开源一下？谢谢！

你好 代码是师弟的，我直接用的他的结果没有跑他代码。他应该没有开源。

**Comment by zuowanbushiwo** [comment]
好的，谢谢！
