### ISSUE TITLE
关于训练过程出现的问题

### ISSUE THREAD

**Issue by Cagemoney** [felixfuyihui/Uformer#8]
作者您好，在复现uformer过程中，我发现，验证模型的时候，enhanced的pesq、stoi等评价指标比noisy低，测试模型时输出是静音。关于网络部分没有进行改动。请问您遇到过这种情况吗？或者您觉得问题出在哪？期望您的早日回复。

**Comment by felixfuyihui** [comment]
训练过程loss正常吗

**Comment by felixfuyihui** [comment]
> 作者您好，在复现uformer过程中，我发现，验证模型的时候，enhanced的pesq、stoi等评价指标比noisy低，测试模型时输出是静音。关于网络部分没有进行改动。请问您遇到过这种情况吗？或者您觉得问题出在哪？期望您的早日回复。


训练过程loss正常吗

**Comment by Cagemoney** [comment]
>
